name: service-master

on:
  # To allow deployment on push to master branch
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yml'
    branches:
      - master
  # To allow manual deployment in production for any branch, tag or commit
  workflow_dispatch:
    inputs:
      REF:
        description: 'Branch, tag or commit SHA1 to build'
        required: false
        default: master
        type: string


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Log current git branch and commit
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current commit message: $(git log -1 --pretty=%B)"
          echo "Input REF: ${{ inputs.REF }}"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Maven
        run: mvn clean package

      - name: Run java project
        run: java -cp target/Sample-Maven-Project-1.0-SNAPSHOT.jar com.example.Main

      - name: echo message
        run: |
          echo "Build is successful"
          ls -alrtR
          echo "${{ toJson(github) }}"
