name: service-master

on:
  # To allow deployment on push to master branch
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yml'
    branches:
      - master
  # To allow manual deployment in production for any branch, tag or commit
  # We can select the workflow yml file from another branch, by selecting the branch in "Use workflow from" dropdown
  # ref is the input parameter to select the branch, tag or commit
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit SHA1 to build'
        required: false
        default: master
        type: string


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # If the ref is a branch, the latest commit from the branch will be checked out
          # If the ref is a tag, the commit for the tag will be checked out
          # If the ref is a commit SHA1, the commit will be checked out
          # If the ref is not provided, the default value is master
          ref: ${{ github.event.inputs.ref }}

      - name: Log current git branch and commit
        run: |
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current commit message: $(git log -1 --pretty=%B)"
          echo "Input ref: ${{ github.event.inputs.ref }}"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Maven
        run: mvn clean package

      - name: Run java project
        run: java -cp target/Sample-Maven-Project-1.0-SNAPSHOT.jar com.example.Main

      - name: echo message
        # Log the GitHub context as a JSON string
        run: |
          echo "Build is successful"
          ls -alrtR
          echo "${{ toJson(github) }}"
